// generated by armkit
import { ArmResource } from '@yetics/armkit-core';
import { Construct } from 'constructs';

/**
 * Microsoft.AnalysisServices/servers
 *
 * @schema Microsoft.AnalysisServices.servers
 */
export class Servers extends ArmResource {
  /**
   * Defines a "Microsoft.AnalysisServices.servers" Arm Template object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: ServersOptions) {
    super(scope, name, {
      ...options,
      armResourceType: 'servers',
    });
  }
}

/**
 * Microsoft.AnalysisServices/servers
 *
 * @schema Microsoft.AnalysisServices.servers
 */
export interface ServersOptions {
  /**
   * @schema Microsoft.AnalysisServices.servers#apiVersion
   */
  readonly apiVersion?: MicrosoftAnalysisServicesServersApiVersion;

  /**
   * Location of the Analysis Services resource.
   *
   * @schema Microsoft.AnalysisServices.servers#location
   */
  readonly location: string;

  /**
   * The name of the Analysis Services server. It must be a minimum of 3 characters, and a maximum of 63.
   *
   * @schema Microsoft.AnalysisServices.servers#name
   */
  readonly name: MicrosoftAnalysisServicesServersNamePattern;

  /**
   * Properties of Analysis Services resource.
   *
   * @schema Microsoft.AnalysisServices.servers#properties
   */
  readonly properties: AnalysisServicesServerProperties;

  /**
   * Represents the SKU name and Azure pricing tier for Analysis Services resource.
   *
   * @schema Microsoft.AnalysisServices.servers#sku
   */
  readonly sku: ResourceSku;

  /**
   * Key-value pairs of additional resource provisioning properties.
   *
   * @schema Microsoft.AnalysisServices.servers#tags
   */
  readonly tags?: MicrosoftAnalysisServicesServersTags;

  /**
   * @schema Microsoft.AnalysisServices.servers#type
   */
  readonly type: MicrosoftAnalysisServicesServersType;

}

export enum MicrosoftAnalysisServicesServersApiVersion {
  "MicrosoftAnalysisServicesServersApiVersion_2017_08_01" = '2017-08-01',
}

/**
 * @schema MicrosoftAnalysisServicesServersName
 */
export class MicrosoftAnalysisServicesServersNamePattern {
  public static pattern(value: string): string {
    return value;
  }
}

/**
 * Properties of Analysis Services resource.
 *
 * @schema #/definitions/AnalysisServicesServerProperties
 */
export interface AnalysisServicesServerProperties {
  /**
   * An array of administrator user identities.
   *
   * @schema #/definitions/AnalysisServicesServerProperties#asAdministrators
   */
  readonly asAdministrators?: ServerAdministrators;

  /**
   * The SAS container URI to the backup container.
   *
   * @schema #/definitions/AnalysisServicesServerProperties#backupBlobContainerUri
   */
  readonly backupBlobContainerUri?: string;

  /**
   * The gateway details.
   *
   * @schema #/definitions/AnalysisServicesServerProperties#gatewayDetails
   */
  readonly gatewayDetails?: GatewayDetails;

  /**
   * An array of firewall rules.
   *
   * @schema #/definitions/AnalysisServicesServerProperties#ipV4FirewallSettings
   */
  readonly ipV4FirewallSettings?: IPv4FirewallSettings;

  /**
   * The managed mode of the server (0 = not managed, 1 = managed).
   *
   * @schema #/definitions/AnalysisServicesServerProperties#managedMode
   */
  readonly managedMode?: number;

  /**
   * How the read-write server's participation in the query pool is controlled.<br/>It can have the following values: <ul><li>readOnly - indicates that the read-write server is intended not to participate in query operations</li><li>all - indicates that the read-write server can participate in query operations</li></ul>Specifying readOnly when capacity is 1 results in error.
   *
   * @schema #/definitions/AnalysisServicesServerProperties#querypoolConnectionMode
   */
  readonly querypoolConnectionMode?: AnalysisServicesServerPropertiesQuerypoolConnectionMode;

  /**
   * The server monitor mode for AS server
   *
   * @schema #/definitions/AnalysisServicesServerProperties#serverMonitorMode
   */
  readonly serverMonitorMode?: number;

  /**
   * Represents the SKU name and Azure pricing tier for Analysis Services resource.
   *
   * @schema #/definitions/AnalysisServicesServerProperties#sku
   */
  readonly sku?: ResourceSku;

}

/**
 * Represents the SKU name and Azure pricing tier for Analysis Services resource.
 *
 * @schema #/definitions/ResourceSku
 */
export interface ResourceSku {
  /**
   * The number of instances in the read only query pool.
   *
   * @schema #/definitions/ResourceSku#capacity
   */
  readonly capacity?: number;

  /**
   * Name of the SKU level.
   *
   * @schema #/definitions/ResourceSku#name
   */
  readonly name: string;

  /**
   * The name of the Azure pricing tier to which the SKU applies.
   *
   * @schema #/definitions/ResourceSku#tier
   */
  readonly tier?: ResourceSkuTier;

}

/**
 * @schema MicrosoftAnalysisServicesServersTags
 */
export interface MicrosoftAnalysisServicesServersTags {
}

export enum MicrosoftAnalysisServicesServersType {
  "MicrosoftAnalysisServicesServersType_MICROSOFT_ANALYSIS_SERVICES_SERVERS" = 'Microsoft.AnalysisServices/servers',
}

/**
 * An array of administrator user identities.
 *
 * @schema #/definitions/ServerAdministrators
 */
export interface ServerAdministrators {
  /**
   * An array of administrator user identities.
   *
   * @schema #/definitions/ServerAdministrators#members
   */
  readonly members?: string[];

}

/**
 * The gateway details.
 *
 * @schema #/definitions/GatewayDetails
 */
export interface GatewayDetails {
  /**
   * Gateway resource to be associated with the server.
   *
   * @schema #/definitions/GatewayDetails#gatewayResourceId
   */
  readonly gatewayResourceId?: string;

}

/**
 * An array of firewall rules.
 *
 * @schema #/definitions/IPv4FirewallSettings
 */
export interface IPv4FirewallSettings {
  /**
   * The indicator of enabling PBI service.
   *
   * @schema #/definitions/IPv4FirewallSettings#enablePowerBIService
   */
  readonly enablePowerBIService?: boolean;

  /**
   * An array of firewall rules.
   *
   * @schema #/definitions/IPv4FirewallSettings#firewallRules
   */
  readonly firewallRules?: IPv4FirewallRule[];

}

export enum AnalysisServicesServerPropertiesQuerypoolConnectionMode {
  ALL = 'All',
  READ_ONLY = 'ReadOnly',
}

export enum ResourceSkuTier {
  DEVELOPMENT = 'Development',
  BASIC = 'Basic',
  STANDARD = 'Standard',
}

/**
 * The detail of firewall rule.
 *
 * @schema #/definitions/IPv4FirewallRule
 */
export interface IPv4FirewallRule {
  /**
   * The rule name.
   *
   * @schema #/definitions/IPv4FirewallRule#firewallRuleName
   */
  readonly firewallRuleName?: string;

  /**
   * The end range of IPv4.
   *
   * @schema #/definitions/IPv4FirewallRule#rangeEnd
   */
  readonly rangeEnd?: string;

  /**
   * The start range of IPv4.
   *
   * @schema #/definitions/IPv4FirewallRule#rangeStart
   */
  readonly rangeStart?: string;

}

