              // generated by armkit
              import { ArmResource } from '@yetics/armkit-core';
              import { Construct } from 'constructs';

              /**
               * Microsoft.OperationalInsights/clusters
               *
               * @schema Microsoft.OperationalInsights.clusters
               */
              export class Clusters extends ArmResource {
                /**
                 * Defines a "Microsoft.OperationalInsights.clusters" Arm Template object
                 * @param scope the scope in which to define this object
                 * @param name a scope-local name for the object
                 * @param options configuration options
                 */
                public constructor(scope: Construct, name: string, options: ClustersOptions) {
                  super(scope, name, {
                    ...options,
                    armResourceType: 'clusters',
                  });
                }
              }

              /**
               * Microsoft.OperationalInsights/workspaces
               *
               * @schema Microsoft.OperationalInsights.workspaces
               */
              export class Workspaces extends ArmResource {
                /**
                 * Defines a "Microsoft.OperationalInsights.workspaces" Arm Template object
                 * @param scope the scope in which to define this object
                 * @param name a scope-local name for the object
                 * @param options configuration options
                 */
                public constructor(scope: Construct, name: string, options: WorkspacesOptions) {
                  super(scope, name, {
                    ...options,
                    armResourceType: 'workspaces',
                  });
                }
              }

              /**
               * Microsoft.OperationalInsights/clusters
               *
               * @schema Microsoft.OperationalInsights.clusters
               */
              export interface ClustersOptions {
                /**
                 * @schema Microsoft.OperationalInsights.clusters#apiVersion
                 */
                readonly apiVersion?: MicrosoftOperationalInsightsClustersApiVersion;

                /**
                 * Identity for the resource.
                 *
                 * @schema Microsoft.OperationalInsights.clusters#identity
                 */
                readonly identity?: Identity;

                /**
                 * The geo-location where the resource lives
                 *
                 * @schema Microsoft.OperationalInsights.clusters#location
                 */
                readonly location: string;

                /**
                 * The name of the Log Analytics cluster.
                 *
                 * @schema Microsoft.OperationalInsights.clusters#name
                 */
                readonly name: MicrosoftOperationalInsightsClustersNamePattern;

                /**
                 * Cluster properties.
                 *
                 * @schema Microsoft.OperationalInsights.clusters#properties
                 */
                readonly properties: ClusterProperties;

                /**
                 * The cluster sku definition.
                 *
                 * @schema Microsoft.OperationalInsights.clusters#sku
                 */
                readonly sku?: ClusterSku;

                /**
                 * Resource tags.
                 *
                 * @schema Microsoft.OperationalInsights.clusters#tags
                 */
                readonly tags?: MicrosoftOperationalInsightsClustersTags;

                /**
                 * @schema Microsoft.OperationalInsights.clusters#type
                 */
                readonly type: MicrosoftOperationalInsightsClustersType;

              }

              /**
               * Microsoft.OperationalInsights/workspaces
               *
               * @schema Microsoft.OperationalInsights.workspaces
               */
              export interface WorkspacesOptions {
                /**
                 * @schema Microsoft.OperationalInsights.workspaces#apiVersion
                 */
                readonly apiVersion?: MicrosoftOperationalInsightsWorkspacesApiVersion;

                /**
                 * The ETag of the workspace.
                 *
                 * @schema Microsoft.OperationalInsights.workspaces#eTag
                 */
                readonly eTag?: string;

                /**
                 * The geo-location where the resource lives
                 *
                 * @schema Microsoft.OperationalInsights.workspaces#location
                 */
                readonly location: string;

                /**
                 * The name of the workspace.
                 *
                 * @schema Microsoft.OperationalInsights.workspaces#name
                 */
                readonly name: MicrosoftOperationalInsightsWorkspacesNamePattern;

                /**
                 * Workspace properties.
                 *
                 * @schema Microsoft.OperationalInsights.workspaces#properties
                 */
                readonly properties: WorkspaceProperties;

                /**
                 * Resource tags.
                 *
                 * @schema Microsoft.OperationalInsights.workspaces#tags
                 */
                readonly tags?: MicrosoftOperationalInsightsWorkspacesTags;

                /**
                 * @schema Microsoft.OperationalInsights.workspaces#type
                 */
                readonly type: MicrosoftOperationalInsightsWorkspacesType;

              }

              export enum MicrosoftOperationalInsightsClustersApiVersion {
                "MicrosoftOperationalInsightsClustersApiVersion_2020_10_01" = '2020-10-01',
              }

              /**
               * Identity for the resource.
               *
               * @schema #/definitions/Identity
               */
              export interface Identity {
                /**
                 * Type of managed service identity.
                 *
                 * @schema #/definitions/Identity#type
                 */
                readonly type: IdentityType;

                /**
                 * The list of user identities associated with the resource. The user identity dictionary key references will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'.
                 *
                 * @schema #/definitions/Identity#userAssignedIdentities
                 */
                readonly userAssignedIdentities?: IdentityUserAssignedIdentities;

              }

              /**
               * @schema MicrosoftOperationalInsightsClustersName
               */
              export class MicrosoftOperationalInsightsClustersNamePattern {
                public static pattern(value: string): string {
                  return value;
                }
              }

              /**
               * Cluster properties.
               *
               * @schema #/definitions/ClusterProperties
               */
              export interface ClusterProperties {
                /**
                 * The list of Log Analytics workspaces associated with the cluster
                 *
                 * @schema #/definitions/ClusterProperties#associatedWorkspaces
                 */
                readonly associatedWorkspaces?: AssociatedWorkspace[];

                /**
                 * Configures whether billing will be only on the cluster or each workspace will be billed by its proportional use. This does not change the overall billing, only how it will be distributed. Default value is 'Cluster'.
                 *
                 * @schema #/definitions/ClusterProperties#billingType
                 */
                readonly billingType?: ClusterPropertiesBillingType;

                /**
                 * The Capacity Reservation properties.
                 *
                 * @schema #/definitions/ClusterProperties#capacityReservationProperties
                 */
                readonly capacityReservationProperties?: CapacityReservationProperties;

                /**
                 * Sets whether the cluster will support availability zones. This can be set as true only in regions where Azure Data Explorer support Availability Zones. This Property can not be modified after cluster creation. Default value is 'true' if region supports Availability Zones.
                 *
                 * @schema #/definitions/ClusterProperties#isAvailabilityZonesEnabled
                 */
                readonly isAvailabilityZonesEnabled?: boolean;

                /**
                 * Configures whether cluster will use double encryption. This Property can not be modified after cluster creation. Default value is 'true'
                 *
                 * @schema #/definitions/ClusterProperties#isDoubleEncryptionEnabled
                 */
                readonly isDoubleEncryptionEnabled?: boolean;

                /**
                 * The key vault properties.
                 *
                 * @schema #/definitions/ClusterProperties#keyVaultProperties
                 */
                readonly keyVaultProperties?: KeyVaultProperties;

              }

              /**
               * The cluster sku definition.
               *
               * @schema #/definitions/ClusterSku
               */
              export interface ClusterSku {
                /**
                 * The capacity value
                 *
                 * @schema #/definitions/ClusterSku#capacity
                 */
                readonly capacity?: number;

                /**
                 * The name of the SKU.
                 *
                 * @schema #/definitions/ClusterSku#name
                 */
                readonly name?: ClusterSkuName;

              }

              /**
               * @schema MicrosoftOperationalInsightsClustersTags
               */
              export interface MicrosoftOperationalInsightsClustersTags {
              }

              export enum MicrosoftOperationalInsightsClustersType {
                "MicrosoftOperationalInsightsClustersType_MICROSOFT_OPERATIONAL_INSIGHTS_CLUSTERS" = 'Microsoft.OperationalInsights/clusters',
              }

              export enum MicrosoftOperationalInsightsWorkspacesApiVersion {
                "MicrosoftOperationalInsightsWorkspacesApiVersion_2020_10_01" = '2020-10-01',
              }

              /**
               * @schema MicrosoftOperationalInsightsWorkspacesName
               */
              export class MicrosoftOperationalInsightsWorkspacesNamePattern {
                public static pattern(value: string): string {
                  return value;
                }
              }

              /**
               * Workspace properties.
               *
               * @schema #/definitions/WorkspaceProperties
               */
              export interface WorkspaceProperties {
                /**
                 * Workspace features.
                 *
                 * @schema #/definitions/WorkspaceProperties#features
                 */
                readonly features?: WorkspacePropertiesFeatures;

                /**
                 * Indicates whether customer managed storage is mandatory for query management.
                 *
                 * @schema #/definitions/WorkspaceProperties#forceCmkForQuery
                 */
                readonly forceCmkForQuery?: boolean;

                /**
                 * The provisioning state of the workspace.
                 *
                 * @schema #/definitions/WorkspaceProperties#provisioningState
                 */
                readonly provisioningState?: WorkspacePropertiesProvisioningState;

                /**
                 * The network access type for accessing Log Analytics ingestion.
                 *
                 * @schema #/definitions/WorkspaceProperties#publicNetworkAccessForIngestion
                 */
                readonly publicNetworkAccessForIngestion?: WorkspacePropertiesPublicNetworkAccessForIngestion;

                /**
                 * The network access type for accessing Log Analytics query.
                 *
                 * @schema #/definitions/WorkspaceProperties#publicNetworkAccessForQuery
                 */
                readonly publicNetworkAccessForQuery?: WorkspacePropertiesPublicNetworkAccessForQuery;

                /**
                 * The workspace data retention in days. Allowed values are per pricing plan. See pricing tiers documentation for details.
                 *
                 * @schema #/definitions/WorkspaceProperties#retentionInDays
                 */
                readonly retentionInDays?: number;

                /**
                 * The SKU (tier) of a workspace.
                 *
                 * @schema #/definitions/WorkspaceProperties#sku
                 */
                readonly sku?: WorkspaceSku;

                /**
                 * The daily volume cap for ingestion.
                 *
                 * @schema #/definitions/WorkspaceProperties#workspaceCapping
                 */
                readonly workspaceCapping?: WorkspaceCapping;

              }

              /**
               * @schema MicrosoftOperationalInsightsWorkspacesTags
               */
              export interface MicrosoftOperationalInsightsWorkspacesTags {
              }

              export enum MicrosoftOperationalInsightsWorkspacesType {
                "MicrosoftOperationalInsightsWorkspacesType_MICROSOFT_OPERATIONAL_INSIGHTS_WORKSPACES" = 'Microsoft.OperationalInsights/workspaces',
              }

              export enum IdentityType {
                SYSTEM_ASSIGNED = 'SystemAssigned',
                USER_ASSIGNED = 'UserAssigned',
                NONE = 'None',
              }

              /**
               * @schema #/definitions/identityUserAssignedIdentities
               */
              export interface IdentityUserAssignedIdentities {
              }

              /**
               * The list of Log Analytics workspaces associated with the cluster.
               *
               * @schema #/definitions/AssociatedWorkspace
               */
              export interface AssociatedWorkspace {
              }

              export enum ClusterPropertiesBillingType {
                CLUSTER = 'Cluster',
                WORKSPACES = 'Workspaces',
              }

              /**
               * The Capacity Reservation properties.
               *
               * @schema #/definitions/CapacityReservationProperties
               */
              export interface CapacityReservationProperties {
              }

              /**
               * The key vault properties.
               *
               * @schema #/definitions/KeyVaultProperties
               */
              export interface KeyVaultProperties {
                /**
                 * The name of the key associated with the Log Analytics cluster.
                 *
                 * @schema #/definitions/KeyVaultProperties#keyName
                 */
                readonly keyName?: string;

                /**
                 * Selected key minimum required size.
                 *
                 * @schema #/definitions/KeyVaultProperties#keyRsaSize
                 */
                readonly keyRsaSize?: number;

                /**
                 * The Key Vault uri which holds they key associated with the Log Analytics cluster.
                 *
                 * @schema #/definitions/KeyVaultProperties#keyVaultUri
                 */
                readonly keyVaultUri?: string;

                /**
                 * The version of the key associated with the Log Analytics cluster.
                 *
                 * @schema #/definitions/KeyVaultProperties#keyVersion
                 */
                readonly keyVersion?: string;

              }

              export enum ClusterSkuName {
                CAPACITY_RESERVATION = 'CapacityReservation',
              }

              /**
               * @schema #/definitions/workspacePropertiesFeatures
               */
              export interface WorkspacePropertiesFeatures {
              }

              export enum WorkspacePropertiesProvisioningState {
                CREATING = 'Creating',
                SUCCEEDED = 'Succeeded',
                FAILED = 'Failed',
                CANCELED = 'Canceled',
                DELETING = 'Deleting',
                PROVISIONING_ACCOUNT = 'ProvisioningAccount',
                UPDATING = 'Updating',
              }

              export enum WorkspacePropertiesPublicNetworkAccessForIngestion {
                ENABLED = 'Enabled',
                DISABLED = 'Disabled',
              }

              export enum WorkspacePropertiesPublicNetworkAccessForQuery {
                ENABLED = 'Enabled',
                DISABLED = 'Disabled',
              }

              /**
               * The SKU (tier) of a workspace.
               *
               * @schema #/definitions/WorkspaceSku
               */
              export interface WorkspaceSku {
                /**
                 * The capacity reservation level for this workspace, when CapacityReservation sku is selected.
                 *
                 * @schema #/definitions/WorkspaceSku#capacityReservationLevel
                 */
                readonly capacityReservationLevel?: number;

                /**
                 * The name of the SKU.
                 *
                 * @schema #/definitions/WorkspaceSku#name
                 */
                readonly name: WorkspaceSkuName;

              }

              /**
               * The daily volume cap for ingestion.
               *
               * @schema #/definitions/WorkspaceCapping
               */
              export interface WorkspaceCapping {
                /**
                 * The workspace daily quota for ingestion.
                 *
                 * @schema #/definitions/WorkspaceCapping#dailyQuotaGb
                 */
                readonly dailyQuotaGb?: number;

              }

              export enum WorkspaceSkuName {
                FREE = 'Free',
                STANDARD = 'Standard',
                PREMIUM = 'Premium',
                PER_NODE = 'PerNode',
                "WorkspaceSkuName_PER_GB2018" = 'PerGB2018',
                STANDALONE = 'Standalone',
                CAPACITY_RESERVATION = 'CapacityReservation',
                LA_CLUSTER = 'LACluster',
              }

