// generated by armkit
import { ArmResource } from '@armkit/core';
import { Construct } from 'constructs';

/**
 * Microsoft.WindowsIoT/deviceServices
 *
 * @schema Microsoft.WindowsIoT.deviceServices
 */
export class DeviceServices extends ArmResource {
  /**
   * Defines a "Microsoft.WindowsIoT.deviceServices" Arm Template object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: DeviceServicesOptions) {
    super(scope, name, {
      ...options,
      armResourceType: 'deviceServices',
    });
  }
}

/**
 * Microsoft.WindowsIoT/deviceServices
 *
 * @schema Microsoft.WindowsIoT.deviceServices
 */
export interface DeviceServicesOptions {
  /**
   * @schema Microsoft.WindowsIoT.deviceServices#apiVersion
   */
  readonly apiVersion?: MicrosoftWindowsIoTDeviceServicesApiVersion;

  /**
   * The Etag field is *not* required. If it is provided in the response body, it must also be provided as a header per the normal ETag convention.
   *
   * @schema Microsoft.WindowsIoT.deviceServices#etag
   */
  readonly etag?: string;

  /**
   * The Azure Region where the resource lives
   *
   * @schema Microsoft.WindowsIoT.deviceServices#location
   */
  readonly location?: string;

  /**
   * The name of the Windows IoT Device Service.
   *
   * @schema Microsoft.WindowsIoT.deviceServices#name
   */
  readonly name: string;

  /**
   * The properties of a Windows IoT Device Service.
   *
   * @schema Microsoft.WindowsIoT.deviceServices#properties
   */
  readonly properties: DeviceServiceProperties;

  /**
   * Resource tags.
   *
   * @schema Microsoft.WindowsIoT.deviceServices#tags
   */
  readonly tags?: MicrosoftWindowsIoTDeviceServicesTags;

  /**
   * @schema Microsoft.WindowsIoT.deviceServices#type
   */
  readonly type: MicrosoftWindowsIoTDeviceServicesType;

}

export enum MicrosoftWindowsIoTDeviceServicesApiVersion {
  "MicrosoftWindowsIoTDeviceServicesApiVersion_2019_06_01" = '2019-06-01',
}

/**
 * The properties of a Windows IoT Device Service.
 *
 * @schema #/definitions/DeviceServiceProperties
 */
export interface DeviceServiceProperties {
  /**
   * Windows IoT Device Service OEM AAD domain
   *
   * @schema #/definitions/DeviceServiceProperties#adminDomainName
   */
  readonly adminDomainName?: string;

  /**
   * Windows IoT Device Service ODM AAD domain
   *
   * @schema #/definitions/DeviceServiceProperties#billingDomainName
   */
  readonly billingDomainName?: string;

  /**
   * Windows IoT Device Service notes.
   *
   * @schema #/definitions/DeviceServiceProperties#notes
   */
  readonly notes?: string;

  /**
   * Windows IoT Device Service device allocation,
   *
   * @schema #/definitions/DeviceServiceProperties#quantity
   */
  readonly quantity?: number;

}

/**
 * @schema MicrosoftWindowsIoTDeviceServicesTags
 */
export interface MicrosoftWindowsIoTDeviceServicesTags {
}

export enum MicrosoftWindowsIoTDeviceServicesType {
  "MicrosoftWindowsIoTDeviceServicesType_MICROSOFT_WINDOWS_IO_T_DEVICE_SERVICES" = 'Microsoft.WindowsIoT/deviceServices',
}

